### ISSUE TITLE
[Meta] Iteration

### ISSUE THREAD

**Issue by marktani** [maticzav/graphql-server-file-upload-example#2]
* [x] look into `AccessDenied` error, example https://my-file-bucket-t9h49nba9r.s3-eu-west-1.amazonaws.com/43de4b08-78b2-4b5c-a5b7-05ee350ee
* [x] change API so uploading multiple files is possible (check https://github.com/graphcool/templates/tree/master/outdated/file-handling/file-proxy#multiple-file-proxy for an example)

---

* [x] update `graphql-yoga` to latest version
* [x] README outdated/inaccurate
* [x] remove mentions of gateway & section 'Project structure' and just refer to boilerplate example instead
